# Generated by Django 5.2.13 on 2026-05-30 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OchecklistReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10)),
                ('creator', models.CharField(max_length=100)),
                ('created', models.DateTimeField()),
                ('event', models.CharField(blank=True, max_length=200, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "O'checklist Report",
                'verbose_name_plural': "O'checklist Reports",
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='OchecklistRunner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runner_id', models.CharField(blank=True, max_length=50, null=True)),
                ('bib', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(max_length=100)),
                ('org', models.CharField(max_length=100)),
                ('card_number', models.CharField(blank=True, max_length=20, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('class_name', models.CharField(max_length=50)),
                ('start_status', models.CharField(choices=[('Started OK', 'Started OK'), ('DNS', 'DNS'), ('Late start', 'Late start')], max_length=20)),
                ('new_card', models.CharField(blank=True, max_length=20, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runners', to='ochecklist.ochecklistreport')),
            ],
            options={
                'verbose_name': "O'checklist Runner",
                'verbose_name_plural': "O'checklist Runners",
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='OchecklistChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dns', models.DateTimeField(blank=True, null=True)),
                ('late_start', models.DateTimeField(blank=True, null=True)),
                ('new_card', models.DateTimeField(blank=True, null=True)),
                ('comment', models.DateTimeField(blank=True, null=True)),
                ('new_runner', models.DateTimeField(blank=True, null=True)),
                ('runner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='changelog', to='ochecklist.ochecklistrunner')),
            ],
            options={
                'verbose_name': "O'checklist Change Log",
                'verbose_name_plural': "O'checklist Change Logs",
            },
        ),
    ]
