"""
Django settings for MeOSDjango project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

try:
    from .dev_settings import *
except ImportError:
    print("Could not import dev_settings")


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Variables d'environnement locales (file gitignoré — absent en dev, présent
# en prod) : DEBUG, ALLOWED_HOSTS, PUBLIC_SITE_URL… Format KEY=value, une
# ligne par variable, # pour les commentaires. Une variable déjà présente dans
# l'environnement réel (interface AlwaysData, systemd…) reste prioritaire.
def _load_env_file(path):
    if not path.is_file():
        return
    for line in path.read_text(encoding='utf-8').splitlines():
        line = line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, _, value = line.partition('=')
        key = key.strip().removeprefix('export ').strip()
        value = value.strip().strip('"').strip("'")
        if key:
            os.environ.setdefault(key, value)


_load_env_file(BASE_DIR / '.env')


def _env_flag(name, default=False):
    """Interprète une variable d'environnement booléenne (1/true/yes/on)."""
    raw = os.environ.get(name)
    if raw is None:
        return default
    return raw.strip().lower() in ('1', 'true', 'yes', 'on')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = DJANGO_SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
# Local : True (pas de .env) · Prod : .env avec DEBUG=0 → active le bloc
# HTTPS/HSTS plus bas (if not DEBUG).
DEBUG = _env_flag('DEBUG', True)

ALLOWED_HOSTS = [
    h.strip() for h in os.environ.get('ALLOWED_HOSTS', '*').split(',') if h.strip()
]  # Prod : .env avec ALLOWED_HOSTS=domaine.tld (défaut local : '*')

APPEND_SLASH = False

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'results',
    'ochecklist',  # Added O'checklist app
    'django_extensions',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'MeOSDjango.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Dossier du projet, prioritaire sur APP_DIRS : indispensable pour
        # surcharger les templates de django.contrib.admin (1er dans
        # INSTALLED_APPS, son dossier templates/ l'emporterait sinon).
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'results.context_processors.site_settings',
                'django.template.context_processors.i18n',
            ],
        },
    },
]

WSGI_APPLICATION = 'MeOSDjango.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': DATABASE_NAME,
        'USER': DATABASE_USER,
        'PASSWORD': DATABASE_PASSWORD,
        'HOST': DATABASE_HOST,
        'PORT': DATABASE_PORT,
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/


LANGUAGE_CODE = 'fr'

# Langues du site. « fr » est la langue source : les chaînes dans le code sont
# en français, seules les traductions (locale/<lang>/LC_MESSAGES/django*.po)
# sont écrites pour les autres langues.
# Le choix de langue est persisté en cookie (LocaleMiddleware) — les URL ne
# changent jamais : les liens MeOS, /gestion-course/<token>/, les /api/ et
# le CSV récapitulatif restent identiques dans toutes les langues.
LANGUAGES = [
    ('fr', 'Français'),
    ('en', 'English'),
    ('sv', 'Svenska'),
    ('de', 'Deutsch'),
]

# Catalogues de traduction du site (au niveau du projet).
LOCALE_PATHS = [BASE_DIR / 'locale']

# Nom du cookie posé par la vue set_language et lu par LocaleMiddleware.
LANGUAGE_COOKIE_NAME = 'co_lang'
# 1 an : le choix de langue survit à la fermeture du navigateur.
LANGUAGE_COOKIE_AGE = 60 * 60 * 24 * 365
LANGUAGE_COOKIE_SAMESITE = 'Lax'

TIME_ZONE = 'Europe/Paris'

USE_I18N = True

USE_TZ = True

# Formats de date localisés (utilisés par les filtres |date:"DATE_FORMAT"…).
# Les valeurs par défaut de Django conviennent :
#   fr → 17/05/2026 · en → May 17, 2026 · sv → 17 maj 2026 · de → 17.05.2026

# HTTPS Settings
# These settings are for production use. For development with runserver_plus,
# HTTPS is handled by the development server itself.
if not DEBUG:  # Only apply in production
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = []

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Logos d'organisateur (upload depuis le formulaire de création de course)
ORG_LOGO_DIR = BASE_DIR / 'org_logo'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ─── MeOS MOP (réception des données en temps réel) ───────────────────────────
# Mot de passe à configurer dans MeOS : Outils > Serveur Online > Mot de passe
# À surcharger via variable d'environnement MOP_PASSWORD en production
#MOP_PASSWORD = os.environ.get('MOP_PASSWORD', 'meos')
MOP_PASSWORD = MEOS_PASSWORD

# ─── SITE CONFIG (override in .env) ────────────────────────────────────────────
SITE_NAME = os.environ.get('SITE_NAME', 'Résultats CO')
SITE_SUBTITLE = os.environ.get('SITE_SUBTITLE', 'https://github.com/Jolatomme/MeOSDjango')
SITE_LOGO_URL = os.environ.get('SITE_LOGO_URL', '')
CLUB_NAME = os.environ.get('CLUB_NAME', 'COCS 73')
CLUB_COLOR_PRIMARY = os.environ.get('CLUB_COLOR_PRIMARY', '#1a6b3c')   # forest green
CLUB_COLOR_ACCENT = os.environ.get('CLUB_COLOR_ACCENT', '#f0a500')     # gold

# URL publique canonique (ex: https://jolatomme.alwaysdata.net) affichée aux
# organisateurs (« URL d'envoi » MeOS, lien de gestion). Vide = déduite de la
# requête courante. À définir en production pour ne jamais afficher un Host
# interne (127.0.0.1, proxy…).
PUBLIC_SITE_URL = os.environ.get('PUBLIC_SITE_URL', '')

# ─── Création de course publique (/creer-course/) ───────────────────────────
# False (ENABLE_RACE_CREATION=0) : /creer-course/ renvoie 404 et le lien
# « Créer une course » est masqué. La gestion /gestion-course/ reste active.
# (helper _env_flag défini en tête de fichier)
ENABLE_RACE_CREATION=True

ENABLE_RACE_CREATION = _env_flag(
    'ENABLE_RACE_CREATION', globals().get('ENABLE_RACE_CREATION', True)
)

# ─── O'checklist Configuration ───────────────────────────────────────────────
# Optional security header authentication for O'checklist endpoint
# Set these in dev_settings.py or environment variables for production
OCHECKLIST_HEADER_KEY = os.environ.get('OCHECKLIST_HEADER_KEY', '')  # e.g., 'X-Ochecklist-Token'
OCHECKLIST_HEADER_VALUE = os.environ.get('OCHECKLIST_HEADER_VALUE', '')  # e.g., 'your-secret-token'
